import OptimizationShowcase from '@/components/optimization-showcase'
import { OptimizedImage } from '@/components/optimized-image'

export default function Playground() {
    return (
        <div className="flex min-h-screen flex-col items-center p-8 sm:p-20 font-sans bg-white dark:bg-black text-black dark:text-white">
            <header className="mb-12 text-center max-w-2xl">
                <h1 className="text-4xl font-bold mb-4">React Best Practices</h1>
                <p className="text-xl text-gray-500 mb-8">
                    A test drive of Vercel&apos;s recommendations for high-performance Next.js applications.
                </p>
                <div className="flex gap-4 justify-center text-sm">
                    <span className="px-3 py-1 rounded-full bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-100">Waterfall Elimination</span>
                    <span className="px-3 py-1 rounded-full bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-100">Server Actions</span>
                    <span className="px-3 py-1 rounded-full bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-100">Core Web Vitals</span>
                </div>
            </header>

            <main className="w-full max-w-4xl space-y-16">
                <OptimizationShowcase />

                <section className="p-6 border rounded-xl shadow-sm bg-gray-50 dark:bg-gray-900/50">
                    <OptimizedImage />
                </section>
            </main>

            <footer className="mt-20 text-gray-400 text-sm">
                Generated by Antigravity
            </footer>
        </div>
    )
}
